"""start

Revision ID: b24712936f8f
Revises: 8c2caeb298c2
Create Date: 2024-05-04 22:00:51.708175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b24712936f8f'
down_revision = '8c2caeb298c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
